---
- hosts: all
  #become: yes
  #become_user: root
  #become_method: su
  gather_facts: True

  tasks:
    - name: collect all facts
      setup:
    - debug: var=ansible_hostname
    
    - name: Retrieve all tags on an instance
      ec2_instance_info:
    
    - name: ping all nodes
      ping:
