---
# Ansible playbook to delete the given file/directory

- name: delete the following directories
  hosts: test_nodes

  tasks:
    - name: delete the directory
      file: path=/etc/ansible/test state=directory state=absent
