---
- hosts: all
  #become: yes
  #become_user: root
  #become_method: su
  gather_facts: True

  tasks:
    - name: collect all facts
      setup:
    - debug: var=hostvars[inventory_hostname]['ansible_enp0s3']['ipv4']['address']
    
    
    - name: ping all nodes
      ping:
