---
- name: ansible playbook to replace the host name in the conf file
  hosts: nodes

  tasks:
    - name: get hostname
      shell: echo $HOSTNAME
      register: result

    - debug:
        var: result


    - name: replace the part of file
      replace:
        dest: /root/t_dir/test.conf
        regexp: 'targeted_text'  # this is to target the text without quotes
        replace: "{{ result.stdout }}"
